[project]
name = "learning-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coverage>=7.6.12",
    "mypy>=1.15.0",
    "pandas>=2.2.3",
    "ruff>=0.9.7",
    "sqlfluff>=3.3.1",
]
